// employees
export const GET_EMPLOYEE_LISTING = "GET_EMPLOYEE_LISTING";
export const SET_EMPLOYEE_LISTING = "SET_EMPLOYEE_LISTING";
export const GET_EMPLOYEE_INFO = "GET_EMPLOYEE_INFO";
export const SET_EMPLOYEE_INFO = "SET_EMPLOYEE_INFO";
export const UPDATE_EMPLOYEE_INFO = "UPDATE_EMPLOYEE_INFO";
export const ADD_EMPLOYEE_INFO = "ADD_EMPLOYEE_INFO";
export const SET_LAST_ADDED_EMPLOYEE_ID = "SET_LAST_ADDED_EMPLOYEE_ID";
export const UNSET_LAST_ADDED_EMPLOYEE_ID = "UNSET_LAST_ADDED_EMPLOYEE_ID";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const EMPLOYEE_ERROR = "EMPLOYEE_ERROR";

//common
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const CHECK_LOGIN = "CHECK_LOGIN";
export const SET_LOGIN_STATUS = "SET_LOGIN_STATUS";
export const GET_USER_LISTING = "GET_USER_LISTING";
export const SET_USER_LISTING = "SET_USER_LISTING";

// review
export const GET_REVIEW_LISTING = "GET_REVIEW_LISTING";
export const SET_REVIEW_LISTING = "SET_REVIEW_LISTING";
export const GET_REVIEW_INFO = "GET_REVIEW_INFO";
export const SET_REVIEW_INFO = "SET_REVIEW_INFO";
export const UPDATE_REVIEW_INFO = "UPDATE_REVIEW_INFO";
export const ADD_REVIEW_INFO = "ADD_REVIEW_INFO";
export const SET_LAST_ADDED_REVIEW_ID = "SET_LAST_ADDED_REVIEW_ID";
export const UNSET_LAST_ADDED_REVIEW_ID = "UNSET_LAST_ADDED_REVIEW_ID";
export const DELETE_REVIEW = "DELETE_REVIEW";
export const SUBMIT_REVIEW = "SUBMIT_REVIEW";
export const REVIEW_ERROR = "REVIEW_ERROR";
