// OTP login
export const INITIATE_SEND_OTP = "INITIATE_SEND_OTP";
export const RESEND_LOGIN_OTP = "RESEND_LOGIN_OTP";
export const SEND_LOGIN_OTP = "SEND_LOGIN_OTP";
export const OTP_SEND_SUCCESS = "OTP_SEND_SUCCESS";
export const OTP_SEND_FAILED = "OTP_SEND_FAILED";
export const OTP_VERIFY_SUCCESS = "OTP_VERIFY_SUCCESS";
export const OTP_VERIFY_FAILED = "OTP_VERIFY_FAILED";
export const CHANGE_NUMBER = "CHANGE_NUMBER";
export const VERIFY_LOGIN_OTP = "VERIFY_LOGIN_OTP";
export const EMIT_LOGIN_EVENT = "EMIT_LOGIN_EVENT";
export const GENERATE_GOOGLE_RECAPTCHA_TOKEN =
  "GENERATE_GOOGLE_RECAPTCHA_TOKEN";

// Google login
export const VALIDATE_GOOGLE_LOGIN = "VALIDATE_GOOGLE_LOGIN";
export const GOOGLE_VERIFY_SUCCESS = "GOOGLE_VERIFY_SUCCESS";
export const GOOGLE_VERIFY_FAILED = "GOOGLE_VERIFY_FAILED";

//common
export const SET_MODULE_OPTIONS = "SET_MODULE_OPTIONS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
